Add new TDTD types, remove deathOfOwner
bcgov/ppr pull request #1189
Opened 2023-02-17 00:55 UTC by owillborn

*Issue #:* /bcgov/entity#15263

*Description of changes:*
- Added new registration types: TRANS_ADMIN, TRANS_AFFIDAVIT, TRANS_WILL
- Updated validation for these new TDTD types
- Updated tests

**Leaving as draft for now as I need to clarify expected functionality for some edge cases**

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

2023-02-20 18:36 UTC, doug-lovett commented on mhr_api/tests/unit/utils/test_registration_validator.py
> +@pytest.mark.parametrize('desc,valid,party_type1,party_type2,text,add_group,message_content', TEST_TRANSFER_DEATH_DATA)
Nice, thanks for adding the new tests.

2023-02-20 18:39 UTC, doug-lovett requested changes
Looks great, just a few comments:
- Increment the api version
- Update the Postman collection to add an example for each of the 3 new registration types, and remove deathOfOwner from the existing transfer examples. Divya will use the Postman examples as a source for testing the API.
- In the future, typically UI changes are captured in a separate PR.

2023-02-21 18:05 UTC, doug-lovett approved these changes
Thanks for making the changes, looks good.

2023-02-21 18:09 UTC, cameron-eyds approved these changes
LGTM!

2023-02-21 18:55 UTC, dimak1 approved these changes
Nice work @owillborn!

2023-02-21 19:51 UTC, merged