Group numbering bug fix
bcgov/ppr pull request #1265
Opened 2023-04-05 23:07 UTC by owillborn

*Issue #:* /bcgov/entity#14866

*Description of changes:*
QA found grouping issues which resulted in incorrect tenancy types being displayed. Refactored how executors are added to groups in the WILL flow. Newly added owners will now always be added to the group from which the owner was deceased, as opposed to creating a new group (happened when all original owners were deleted/marked deceased).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

2023-04-05 23:22 UTC, dimak1 requested changes
All looks good but please add a unit test. You can reference existing test for WILL transfer in `MhrTransferHomeOwners.spec.ts`.

2023-04-05 23:22 UTC, dimak1 commented on ppr-ui/src/composables/mhrRegistration/useHomeOwners.ts
> +    let transferDefaultId = null
Setting `transferDefaultId = groupId` and removing the `else` clause will have the same effect.

2023-04-05 23:57 UTC, cameron-eyds commented
Just a heads up, there was a very explicit requirement that a new owner added after all owners had been deceased was its own thing. Here is a pic of what i mean, hopefully this is preserved! 

![Screen Shot 2023-04-05 at 4 56 53 PM](https://user-images.githubusercontent.com/53542131/230239057-97278d83-1018-4e16-adf1-f5a4522801fe.png)

2023-04-06 00:02 UTC, dimak1 commented
@cameron-eyds for WILL transfers, the requirement is that Executor is added to the group with one or all deleted owners. Also, there is an error message _All owners must be deceased and an executor added._ 


<img width="229" alt="Screen Shot 2023-04-05 at 5 00 07 PM" src="https://user-images.githubusercontent.com/2333290/230239435-7fbda897-4b34-430b-9c67-5345c0275f8a.png">

2023-04-06 01:02 UTC, cameron-eyds commented
> @cameron-eyds for WILL transfers, the requirement is that Executor is added to the group with one or all deleted owners. Also, there is an error message _All owners must be deceased and an executor added._
> 
> <img alt="Screen Shot 2023-04-05 at 5 00 07 PM" width="229" src="https://user-images.githubusercontent.com/2333290/230239435-7fbda897-4b34-430b-9c67-5345c0275f8a.png">

O see, so the logic is tied to the party type, sounds good!
Just wanted to highlight there was some other requirements in another scenario, similar but opposite :)

2023-04-06 01:05 UTC, dimak1 commented
@cameron-eyds yes, looks like each transfer type has its own requirements.

2023-04-06 14:23 UTC, cameron-eyds commented on ppr-ui/src/composables/mhrRegistration/useHomeOwners.ts
> +         getMhrTransferType.value?.transferType === ApiTransferTypes.TO_EXECUTOR_PROBATE_WILL)) {
O wow, so you can remove the group as a whole and still add to it? 
Wouldn't the whole group in this state?

![Screen Shot 2023-04-06 at 7 22 24 AM](https://user-images.githubusercontent.com/53542131/230406438-a5e06197-84ff-4457-a57d-ac8e778d4471.png)

2023-04-06 14:23 UTC, cameron-eyds reviewed
Looks good, no other comments than Dima's!

2023-04-06 15:00 UTC, dimak1 commented on ppr-ui/src/composables/mhrRegistration/useHomeOwners.ts
> +         getMhrTransferType.value?.transferType === ApiTransferTypes.TO_EXECUTOR_PROBATE_WILL)) {
In Will Transfers, all owners in the group could be removed but we do not show 'Previous Owner Group' text as well as Group Undo button. To this flow is not like others.

2023-04-06 15:02 UTC, doug-lovett approved these changes
Looks good, no additional comments.

2023-04-06 15:55 UTC, cameron-eyds commented on ppr-ui/src/composables/mhrRegistration/useHomeOwners.ts
> +         getMhrTransferType.value?.transferType === ApiTransferTypes.TO_EXECUTOR_PROBATE_WILL)) {
A lot of layers!
I just feel bad for Divya trying to remember all these scenarios haha

2023-04-06 15:58 UTC, dimak1 commented on ppr-ui/src/composables/mhrRegistration/useHomeOwners.ts
> +         getMhrTransferType.value?.transferType === ApiTransferTypes.TO_EXECUTOR_PROBATE_WILL)) {
Yes, and implementing them is not fun either, a lot of conflicting validations.

2023-04-06 18:42 UTC, dimak1 approved these changes
@owillborn looks great with a test! Should make you feel more confident that your code works. Good job!

2023-04-06 19:05 UTC, cameron-eyds approved these changes

2023-04-06 22:13 UTC, doug-lovett approved these changes
Looks good.

2023-04-11 01:56 UTC, dimak1 commented
I run into the same issue when working with WILL transfers. I will copy the code for now, but we should merge it as soon as we can.

2023-04-11 14:27 UTC, merged