6438 API debtor business search. Also some work on building detail re…
bcgov/ppr pull request #15
Opened 2021-03-04 17:38 UTC by doug-lovett

…sults JSON.

Signed-off-by: Doug Lovett <doug@diamante.ca>

2021-03-08 22:01 UTC, thorwolpert requested changes
Some changes to look at.
for tests, maybe look at leveraging: pytest.mark.parametrize

2021-03-08 22:01 UTC, thorwolpert commented on ppr-api/README.md
>  1. Run `pip install .`
this should be included in the Makefile, if not, let me know and I'll update it.

2021-03-08 22:01 UTC, thorwolpert commented on ppr-api/src/ppr_api/models/client_party.py
> +from .address import Address  # noqa: F401 pylint: disable=unused-import
we try and put in the reason for the override after a **;**

2021-03-08 22:01 UTC, thorwolpert commented on ppr-api/src/ppr_api/models/db.py
> -#from sqlalchemy_continuum import make_versioned
you can remove all the continuum bits from the models, as PPR wont use it for versioning

2021-03-08 22:01 UTC, thorwolpert commented on ppr-api/src/ppr_api/models/financing_statement.py
> +# from sqlalchemy import event
you can just remove these.
when Sonarcloud is hooked up to this, it'll complain about commented out code.

2021-03-08 22:01 UTC, thorwolpert commented on ppr-api/src/ppr_api/models/financing_statement.py
> +from .registration import Registration  # noqa: F401 pylint: disable=unused-import
we keep the comments as to why a lint was disabled

2021-03-08 22:01 UTC, thorwolpert commented on ppr-api/src/ppr_api/models/search_client.py
> +# flake8: noqa Q000,E122,E131
please add comments as to why the lint exclusions?

2021-03-08 22:01 UTC, thorwolpert commented on ppr-api/src/ppr_api/models/search_client.py
> +        """Execute a search by the previously set search type and criteria."""
the exception from save just keeps floating up?

2021-03-08 22:01 UTC, thorwolpert commented on ppr-api/src/ppr_api/models/search_result.py
> +# from sqlalchemy import event
you can remove these

2021-03-08 22:01 UTC, thorwolpert commented on ppr-api/src/ppr_api/models/trust_indenture.py
> +from .registration import Registration  # noqa: F401 pylint: disable=unused-import
we like to keep the comments as to why the linter is suppressed

2021-03-08 22:01 UTC, thorwolpert commented on ppr-api/src/ppr_api/services/payment/__init__.py
> +PAYMENT_SVC_URL = os.getenv('PAYMENT_SVC_URL')
this is a bad pattern for flask that crept into the other services, so don't follow it.
should come from , current_app.config.get('PAYMENT_SVC_URL')

2021-03-08 22:01 UTC, thorwolpert commented on ppr-api/src/ppr_api/services/payment/client/__init__.py
> +PAYMENT_SVC_PREFIX = os.getenv('PAYMENT_SVC_PREFIX', 'api/v1/')
this is a bad pattern for flask that crept into the other services, so don't follow it.
should come from , current_app.config.get('PAYMENT_SVC_URL')

2021-03-08 22:01 UTC, thorwolpert commented on ppr-api/tests/unit/api/test_amendment.py
> +def test_amendment_valid_am_200(session, client, jwt):
Could these be table driven tests?

2021-03-08 22:57 UTC, doug-lovett commented on ppr-api/README.md
>  1. Run `pip install .`
The makefile also has setup-venv and install-dev.

2021-03-08 22:59 UTC, doug-lovett commented on ppr-api/src/ppr_api/models/client_party.py
> +from .address import Address  # noqa: F401 pylint: disable=unused-import
With the comment flake8 generates:
src/ppr_api/models/client_party.py:21:1: I003 isort expected 1 blank line in imports, found 0
src/ppr_api/models/client_party.py:21:1: I003 isort expected 1 blank line in imports, found 0
I'll put the comment in a separate line.

2021-03-08 23:14 UTC, doug-lovett commented on ppr-api/src/ppr_api/models/db.py
> -#from sqlalchemy_continuum import make_versioned
Continnuum references and versioning removed.

2021-03-08 23:19 UTC, doug-lovett commented on ppr-api/src/ppr_api/models/financing_statement.py
> +# from sqlalchemy import event
Removed.

2021-03-08 23:23 UTC, doug-lovett commented on ppr-api/src/ppr_api/models/financing_statement.py
> +from .registration import Registration  # noqa: F401 pylint: disable=unused-import
Comments restored. Initially they were generating flake8 messages.

2021-03-08 23:25 UTC, doug-lovett commented on ppr-api/src/ppr_api/models/search_result.py
> +# from sqlalchemy import event
Removed.

2021-03-08 23:27 UTC, doug-lovett commented on ppr-api/src/ppr_api/models/trust_indenture.py
> +from .registration import Registration  # noqa: F401 pylint: disable=unused-import
When I restore the comment I see these flake8 messages:
src/ppr_api/models/trust_indenture.py:18:1: I003 isort expected 1 blank line in imports, found 0
src/ppr_api/models/trust_indenture.py:18:1: I003 isort expected 1 blank line in imports, found 0
src/ppr_api/models/trust_indenture.py:18:121: E501 line too long (121 > 120 characters)
Added comment as a separate line.

2021-03-08 23:36 UTC, doug-lovett commented on ppr-api/tests/unit/api/test_amendment.py
> +def test_amendment_valid_am_200(session, client, jwt):
Yes, I'll keep that in mind as they are maintained. Maybe with https://docs.pytest.org/en/latest/parametrize.html

2021-03-08 23:43 UTC, thorwolpert commented on ppr-api/tests/unit/api/test_amendment.py
> +def test_amendment_valid_am_200(session, client, jwt):
yep, lots of examples about eg. https://github.com/bcgov/lear/blob/master/queue_services/entity-filer/tests/unit/test_configuration.py

2021-03-08 23:44 UTC, doug-lovett commented on ppr-api/src/ppr_api/models/search_client.py
> +        """Execute a search by the previously set search type and criteria."""
Yes, it's just logging the occurrence and creating a specific message. The resource formats BusinessException responses.

2021-03-08 23:58 UTC, doug-lovett commented on ppr-api/src/ppr_api/models/search_client.py
> +# flake8: noqa Q000,E122,E131
Adding comments:
# Disable Q000: Allow query strings to be in double quotation marks that contain single quotation marks.
# Disable E122: allow query strings to be more human readable.
# Disable E131: allow query strings to be more human readable.

2021-03-09 01:07 UTC, doug-lovett commented on ppr-api/src/ppr_api/services/payment/__init__.py
> +PAYMENT_SVC_URL = os.getenv('PAYMENT_SVC_URL')
Remove: only required in the client.

2021-03-09 01:07 UTC, doug-lovett commented on ppr-api/src/ppr_api/services/payment/client/__init__.py
> +PAYMENT_SVC_PREFIX = os.getenv('PAYMENT_SVC_PREFIX', 'api/v1/')
Changed os.getenv to current_app.config.get.

2021-03-10 21:13 UTC, thorwolpert approved these changes

2021-03-10 21:13 UTC, merged