secure party change modal and ux items
bcgov/ppr pull request #188
Opened 2021-08-30 17:40 UTC by jordiwes

*Issue #:* /bcgov/entity#7864

*Description of changes:*
- some ux updates for other registrations
- secured party change modal

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

2021-08-30 19:10 UTC, doug-lovett commented on ppr-ui/src/components/parties/SecuredParties.vue
> +        parties.registeringParty.businessName = 'Bank of Montreal'
Should this be removed?

2021-08-30 19:28 UTC, jordiwes commented on ppr-ui/src/components/parties/SecuredParties.vue
> +        parties.registeringParty.businessName = 'Bank of Montreal'
whoops!

2021-08-30 19:32 UTC, doug-lovett approved these changes

2021-08-30 20:27 UTC, doug-lovett approved these changes
Adding OT other type description looks good.

2021-08-30 21:47 UTC, kialj876 requested changes
Looks good to me, but can you add in some tests please? New dialogue should have a test suite and we should probably test it coming up wherever its needed (should be pretty similar to existing tests we have for the confirmation dialog).
I also think you could've used the confirmation dialog for this one (would've needed an 'if' around the checkbox is the only change right?), but it doesn't really matter. Would've been less test setup for ya though!

2021-08-31 17:51 UTC, jordiwes commented
I added some tests :)

2021-08-31 18:10 UTC, kialj876 approved these changes
Thanks for adding those in!

2021-08-31 18:21 UTC, merged