8701 - changes for renewal
bcgov/ppr pull request #225
Opened 2021-09-13 17:06 UTC by jordiwes

*Issue #:* /bcgov/entity#8701

*Description of changes:*
- add fee summary
- additional rules for renew

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

2021-09-13 17:45 UTC, kialj876 commented on ppr-ui/src/composables/fees/factories/useFeeSummary.ts
>    if (feeType === FeeSummaryTypes.RENEW) {
hey Steph, can this just be combined into the FeeSummaryTypes.NEW block? ```if ([FeeSummaryTypes.RENEW, FeeSummaryTypes.NEW].includes(feeType)) ....```

2021-09-13 17:46 UTC, kialj876 requested changes
Looks good, just one comment and feeSummary needs a test suite update for renewals! Also the label probably needs to change (right now it is under a FUTURE comment and is defaulting to 'Renewal')

2021-09-13 19:23 UTC, doug-lovett reviewed
Nothing to add in addition to Kial's review.

2021-09-13 20:16 UTC, doug-lovett approved these changes

2021-09-13 20:49 UTC, kialj876 commented
Hey Steph, I think you'll need to add renewal to the condition on line 80 in useFeeSummary (and that should fix the test failure too)

2021-09-14 00:16 UTC, jordiwes commented
Thanks Kial, I made those changes

2021-09-14 15:44 UTC, merged