8874 court order validation
bcgov/ppr pull request #314
Opened 2021-10-18 21:20 UTC by jordiwes

*Issue #:* /bcgov/entity#8874

*Description of changes:*
- bunch of items from ux
- court order validation

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

2021-10-18 21:51 UTC, doug-lovett approved these changes

2021-10-18 23:40 UTC, kialj876 approved these changes

2021-10-18 23:41 UTC, kialj876 requested changes
Looks good, but test is failing

2021-10-19 15:40 UTC, kialj876 approved these changes

2021-10-19 15:52 UTC, merged