9141 vehicle collateral summary
bcgov/ppr pull request #324
Opened 2021-10-21 20:17 UTC by jordiwes

*Issue #:* /bcgov/entity#9141

*Description of changes:*
- amendment summary of vehicle collateral

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

2021-10-22 18:45 UTC, doug-lovett approved these changes
again looks good.

2021-10-26 16:19 UTC, kialj876 approved these changes
LGTM

2021-10-26 16:19 UTC, kialj876 requested changes
Looks good, but tests are failing :(

2021-10-27 15:40 UTC, kialj876 approved these changes

2021-10-27 15:46 UTC, merged