von lookup ux
bcgov/ppr pull request #334
Opened 2021-10-27 22:20 UTC by jordiwes

*Issue #:* /bcgov/entity#9065

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

2021-10-27 22:41 UTC, kialj876 approved these changes
Looks good!

2021-10-27 22:42 UTC, kialj876 requested changes
looks good but test fails :(

2021-10-27 22:52 UTC, jordiwes commented
> looks good but test fails :(

testy fixy

2021-10-27 23:27 UTC, kialj876 approved these changes

2021-10-28 00:04 UTC, doug-lovett approved these changes

2021-10-28 15:30 UTC, merged