Update README.md
bcgov/ppr pull request #52
Opened 2021-04-22 23:22 UTC by jordiwes

give the option to start with directory for easier access

*Issue #:* /bcgov/entity###

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

2021-04-23 02:11 UTC, thorwolpert requested changes

2021-04-23 02:11 UTC, thorwolpert commented on oracle-db/README.md
> +	$ docker run -d -it --name <Oracle-DB>-v /mnt/c/Users/username/Containers/bcregistry/oradata/OracleDBData:/ORCL store/oracle/database-enterprise:12.2.0.1
needs a space before the ```-v```

2021-04-23 17:36 UTC, jordiwes commented on oracle-db/README.md
> +	$ docker run -d -it --name <Oracle-DB>-v /mnt/c/Users/username/Containers/bcregistry/oradata/OracleDBData:/ORCL store/oracle/database-enterprise:12.2.0.1
fixed

2021-04-27 17:22 UTC, thorwolpert approved these changes

2021-04-27 17:22 UTC, merged