Reset all form validations upon MH registration submission
bcgov/ppr pull request #964
Opened 2022-09-27 15:30 UTC by owillborn

*Issue #:* /bcgov/entity###

*Description of changes:*
- Added function resetAllValidations to reset the forms along the stepper once the MH registration is submitted

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

2022-09-27 15:48 UTC, doug-lovett approved these changes
Looks good to me.

2022-09-27 16:01 UTC, cameron-eyds commented on ppr-ui/src/views/newMhrRegistration/MhrRegistration.vue
> +
Looks good but could you move this into the validation composable?

2022-09-27 16:02 UTC, cameron-freshworks commented on ppr-ui/src/views/newMhrRegistration/MhrRegistration.vue
> +
useMhrValidations

2022-09-27 16:02 UTC, cameron-freshworks reviewed
Good job! Just 1 comment

2022-09-27 16:05 UTC, owillborn commented on ppr-ui/src/views/newMhrRegistration/MhrRegistration.vue
> +
For sure! Would that composable file be "useMhrValidations.ts"?

2022-09-27 16:07 UTC, owillborn commented on ppr-ui/src/views/newMhrRegistration/MhrRegistration.vue
> +
Gotcha thanks!

2022-09-27 19:02 UTC, ChasBoucher approved these changes
Other than Camerons comments.  Looks Good.

2022-09-30 00:49 UTC, dimak1 requested changes
As per Cameron's comment, please move validation to a composable. Thanks!

2022-10-03 15:57 UTC, cameron-freshworks approved these changes
Looks good, thank you!

2022-10-03 15:58 UTC, dimak1 approved these changes

2022-10-03 16:37 UTC, merged